<x-app-layout variant="student" pageTitle="Lịch sử điểm danh">
    {{-- DESKTOP HISTORY --}}
    <div class="hidden lg:block w-full h-full p-6 lg:p-8 max-w-7xl mx-auto">
        <div class="space-y-6 animate-in fade-in duration-300">
            <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h1 class="text-2xl font-black text-slate-900 tracking-tight flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-history w-6.5 h-6.5 text-blue-600 shrink-0" aria-hidden="true"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"></path><path d="M3 3v5h5"></path><path d="M12 7v5l4 2"></path></svg>
                        Lịch sử điểm danh
                    </h1>
                    <p class="text-xs text-slate-500 font-semibold mt-1">Xem và tra cứu nhật ký học bạ tích luỹ điểm danh SAMS điện tử của sinh viên</p>
                </div>
                <div class="flex gap-4 text-xs text-slate-500 font-semibold select-none shrink-0">
                    <span class="px-3.5 py-1.5 bg-slate-100 border border-slate-200 rounded-xl flex items-center gap-1.5">Đã ghi nhận: <strong class="text-slate-800 font-bold font-mono">5</strong> buổi</span>
                    <span class="px-3.5 py-1.5 bg-blue-50 text-blue-700 border border-blue-200 rounded-xl flex items-center gap-1.5">Hiển thị: <strong class="font-bold font-mono text-blue-850">6</strong> kết quả</span>
                </div>
            </div>
            
            <div class="bg-white border border-slate-200 rounded-3xl p-5 shadow-sm space-y-4">
                <div class="flex items-center gap-2 text-xs font-bold text-slate-705 pb-2 border-b border-slate-100">
                    <span class="bg-blue-100 p-1.5 rounded-lg text-blue-600"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-history w-3.5 h-3.5" aria-hidden="true"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"></path><path d="M3 3v5h5"></path><path d="M12 7v5l4 2"></path></svg></span>
                    <span>BỘ LỌC TÌM KIẾM CHUYÊN BẠ</span>
                </div>
                <div class="grid grid-cols-1 md:grid-cols-12 gap-5">
                    <div class="md:col-span-4 space-y-1.5"><label class="text-[10px] uppercase font-black text-slate-405 tracking-wide block select-none">Theo môn học</label><select class="bg-slate-50 border border-slate-200 rounded-xl px-3 py-2.5 text-xs font-semibold text-slate-700 focus:border-blue-500 focus:ring-1 focus:ring-blue-550 outline-none w-full cursor-pointer"><option value="all">Tất cả môn học</option><option value="DB101">DB101 - Thiết kế &amp; Quản trị SQL</option><option value="PY201">PY201 - Phát triển Web Python</option><option value="PH102">PH102 - Vật lý đại cương 2</option><option value="NET301">NET301 - Lý thuyết Mạng Máy Tính</option><option value="CS402">CS402 - Thuật toán Nâng cao</option></select></div>
                    <div class="md:col-span-4 space-y-1.5"><label class="text-[10px] uppercase font-black text-slate-405 tracking-wide block select-none">Theo học kỳ</label><select class="bg-slate-50 border border-slate-200 rounded-xl px-3 py-2.5 text-xs font-semibold text-slate-700 focus:border-blue-550 focus:ring-1 focus:ring-blue-550 outline-none w-full cursor-pointer"><option value="all">Tất cả học kỳ</option><option value="Học kỳ I (2025-2026)">Học kỳ I (2025-2026)</option><option value="Học kỳ II (2025-2026)">Học kỳ II (2025-2026)</option></select></div>
                    <div class="md:col-span-4 space-y-1.5">
                        <label class="text-[10px] uppercase font-black text-slate-405 tracking-wide block select-none">Theo khoảng thời gian</label>
                        <div class="grid grid-cols-2 gap-2">
                            <div><input class="bg-slate-50 border border-slate-200 rounded-xl px-2 py-2 text-xs font-semibold text-slate-700 focus:border-blue-550 focus:ring-1 focus:ring-blue-550 outline-none w-full" type="date" value=""></div>
                            <div><input class="bg-slate-50 border border-slate-200 rounded-xl px-2 py-2 text-xs font-semibold text-slate-700 focus:border-blue-550 focus:ring-1 focus:ring-blue-550 outline-none w-full" type="date" value=""></div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
                <div class="bg-white border border-slate-200 rounded-3xl p-6 shadow-sm overflow-hidden col-span-12">
                    <div class="border-b border-slate-100 pb-3 mb-4 flex justify-between items-center select-none">
                        <h4 class="text-xs font-black text-slate-900 uppercase">Nhật ký bạ điểm danh tích luỹ</h4>
                        <span class="text-[9px] text-slate-400 font-mono tracking-widest">SAMS SECURE LEDGER PRO</span>
                    </div>
                    <div class="overflow-x-auto select-text font-sans">
                        <table class="w-full text-left text-xs font-semibold text-slate-655 border-collapse">
                            <thead>
                                <tr class="border-b border-slate-100 text-[10px] uppercase tracking-wider text-slate-400 font-black select-none">
                                    <th class="py-2.5 pr-4 pl-1">Ngày</th>
                                    <th class="py-2.5 px-4">Môn học</th>
                                    <th class="py-2.5 px-4">Lớp học</th>
                                    <th class="py-2.5 px-4">Trạng thái</th>
                                    <th class="py-2.5 px-4">Hình thức</th>
                                    <th class="py-2.5 px-2 text-right">Chi tiết</th>
                                </tr>
                            </thead>
                            <tbody class="divide-y divide-slate-50 text-[11px] font-medium text-slate-600">
                                <tr class="hover:bg-blue-50/15 transition-all cursor-pointer "><td class="py-3.5 pr-4 pl-1 font-mono text-slate-950 font-bold whitespace-nowrap"><span class="flex items-center gap-1.5"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock w-3.5 h-3.5 text-slate-400 shrink-0" aria-hidden="true"><path d="M12 6v6l4 2"></path><circle cx="12" cy="12" r="10"></circle></svg>04/06/2026</span></td><td class="py-3.5 px-4 text-slate-800 font-extrabold max-w-[170px] truncate" title="DB101: Thiết kế &amp; Quản trị SQL">Thiết kế &amp; Quản trị SQL</td><td class="py-3.5 px-4 font-mono text-slate-650 font-bold leading-none uppercase">DB101</td><td class="py-3.5 px-4 font-sans text-xs"><span class="inline-flex items-center gap-1 bg-emerald-50 text-emerald-700 border border-emerald-100 text-[10px] font-bold px-2 py-0.5 rounded-lg uppercase whitespace-nowrap">Có mặt</span></td><td class="py-3.5 px-4 font-mono text-slate-600 font-bold text-[10px] whitespace-nowrap"><span class="bg-slate-100 text-slate-700 px-2 py-0.5 rounded-md text-[9.5px]">QR + GPS</span></td><td class="py-3.5 px-2 text-right"><button class="inline-flex items-center gap-1 bg-blue-50 hover:bg-blue-100 text-blue-700 font-extrabold px-2.5 py-1 rounded-lg text-[9.5px] border-none tracking-tight transition-all active:scale-95 cursor-pointer"><span>Xem chi tiết</span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-right w-3.5 h-3.5 text-blue-600 shrink-0" aria-hidden="true"><path d="m9 18 6-6-6-6"></path></svg></button></td></tr>
                                <tr class="hover:bg-blue-50/15 transition-all cursor-pointer "><td class="py-3.5 pr-4 pl-1 font-mono text-slate-950 font-bold whitespace-nowrap"><span class="flex items-center gap-1.5"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock w-3.5 h-3.5 text-slate-400 shrink-0" aria-hidden="true"><path d="M12 6v6l4 2"></path><circle cx="12" cy="12" r="10"></circle></svg>03/06/2026</span></td><td class="py-3.5 px-4 text-slate-800 font-extrabold max-w-[170px] truncate" title="PY201: Phát triển Web Python">Phát triển Web Python</td><td class="py-3.5 px-4 font-mono text-slate-650 font-bold leading-none uppercase">PY201</td><td class="py-3.5 px-4 font-sans text-xs"><span class="inline-flex items-center gap-1 bg-amber-50 text-amber-700 border border-amber-100 text-[10px] font-bold px-2 py-0.5 rounded-lg uppercase whitespace-nowrap">Muộn</span></td><td class="py-3.5 px-4 font-mono text-slate-600 font-bold text-[10px] whitespace-nowrap"><span class="bg-slate-100 text-slate-700 px-2 py-0.5 rounded-md text-[9.5px]">QR + GPS</span></td><td class="py-3.5 px-2 text-right"><button class="inline-flex items-center gap-1 bg-blue-50 hover:bg-blue-100 text-blue-700 font-extrabold px-2.5 py-1 rounded-lg text-[9.5px] border-none tracking-tight transition-all active:scale-95 cursor-pointer"><span>Xem chi tiết</span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-right w-3.5 h-3.5 text-blue-600 shrink-0" aria-hidden="true"><path d="m9 18 6-6-6-6"></path></svg></button></td></tr>
                                <tr class="hover:bg-blue-50/15 transition-all cursor-pointer "><td class="py-3.5 pr-4 pl-1 font-mono text-slate-950 font-bold whitespace-nowrap"><span class="flex items-center gap-1.5"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock w-3.5 h-3.5 text-slate-400 shrink-0" aria-hidden="true"><path d="M12 6v6l4 2"></path><circle cx="12" cy="12" r="10"></circle></svg>02/06/2026</span></td><td class="py-3.5 px-4 text-slate-800 font-extrabold max-w-[170px] truncate" title="PH102: Vật lý đại cương 2">Vật lý đại cương 2</td><td class="py-3.5 px-4 font-mono text-slate-650 font-bold leading-none uppercase">PH102</td><td class="py-3.5 px-4 font-sans text-xs"><span class="inline-flex items-center gap-1 bg-rose-50 text-rose-700 border border-rose-100 text-[10px] font-bold px-2 py-0.5 rounded-lg uppercase whitespace-nowrap">Vắng</span></td><td class="py-3.5 px-4 font-mono text-slate-600 font-bold text-[10px] whitespace-nowrap"><span class="bg-slate-100 text-slate-700 px-2 py-0.5 rounded-md text-[9.5px]">Thủ công</span></td><td class="py-3.5 px-2 text-right"><button class="inline-flex items-center gap-1 bg-blue-50 hover:bg-blue-100 text-blue-700 font-extrabold px-2.5 py-1 rounded-lg text-[9.5px] border-none tracking-tight transition-all active:scale-95 cursor-pointer"><span>Xem chi tiết</span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-right w-3.5 h-3.5 text-blue-600 shrink-0" aria-hidden="true"><path d="m9 18 6-6-6-6"></path></svg></button></td></tr>
                                <tr class="hover:bg-blue-50/15 transition-all cursor-pointer "><td class="py-3.5 pr-4 pl-1 font-mono text-slate-950 font-bold whitespace-nowrap"><span class="flex items-center gap-1.5"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock w-3.5 h-3.5 text-slate-400 shrink-0" aria-hidden="true"><path d="M12 6v6l4 2"></path><circle cx="12" cy="12" r="10"></circle></svg>29/05/2026</span></td><td class="py-3.5 px-4 text-slate-800 font-extrabold max-w-[170px] truncate" title="NET301: Lý thuyết Mạng Máy Tính">Lý thuyết Mạng Máy Tính</td><td class="py-3.5 px-4 font-mono text-slate-650 font-bold leading-none uppercase">NET301</td><td class="py-3.5 px-4 font-sans text-xs"><span class="inline-flex items-center gap-1 bg-blue-50 text-blue-700 border border-blue-105 text-[10px] font-bold px-2 py-0.5 rounded-lg uppercase whitespace-nowrap">Có phép</span></td><td class="py-3.5 px-4 font-mono text-slate-600 font-bold text-[10px] whitespace-nowrap"><span class="bg-slate-100 text-slate-700 px-2 py-0.5 rounded-md text-[9.5px]">Thủ công</span></td><td class="py-3.5 px-2 text-right"><button class="inline-flex items-center gap-1 bg-blue-50 hover:bg-blue-100 text-blue-700 font-extrabold px-2.5 py-1 rounded-lg text-[9.5px] border-none tracking-tight transition-all active:scale-95 cursor-pointer"><span>Xem chi tiết</span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-right w-3.5 h-3.5 text-blue-600 shrink-0" aria-hidden="true"><path d="m9 18 6-6-6-6"></path></svg></button></td></tr>
                                <tr class="hover:bg-blue-50/15 transition-all cursor-pointer "><td class="py-3.5 pr-4 pl-1 font-mono text-slate-950 font-bold whitespace-nowrap"><span class="flex items-center gap-1.5"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock w-3.5 h-3.5 text-slate-400 shrink-0" aria-hidden="true"><path d="M12 6v6l4 2"></path><circle cx="12" cy="12" r="10"></circle></svg>28/05/2026</span></td><td class="py-3.5 px-4 text-slate-800 font-extrabold max-w-[170px] truncate" title="CS402: Thuật toán Nâng cao">Thuật toán Nâng cao</td><td class="py-3.5 px-4 font-mono text-slate-650 font-bold leading-none uppercase">CS402</td><td class="py-3.5 px-4 font-sans text-xs"><span class="inline-flex items-center gap-1 bg-emerald-50 text-emerald-700 border border-emerald-100 text-[10px] font-bold px-2 py-0.5 rounded-lg uppercase whitespace-nowrap">Có mặt</span></td><td class="py-3.5 px-4 font-mono text-slate-600 font-bold text-[10px] whitespace-nowrap"><span class="bg-slate-100 text-slate-700 px-2 py-0.5 rounded-md text-[9.5px]">QR + GPS</span></td><td class="py-3.5 px-2 text-right"><button class="inline-flex items-center gap-1 bg-blue-50 hover:bg-blue-100 text-blue-700 font-extrabold px-2.5 py-1 rounded-lg text-[9.5px] border-none tracking-tight transition-all active:scale-95 cursor-pointer"><span>Xem chi tiết</span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-right w-3.5 h-3.5 text-blue-600 shrink-0" aria-hidden="true"><path d="m9 18 6-6-6-6"></path></svg></button></td></tr>
                                <tr class="hover:bg-blue-50/15 transition-all cursor-pointer "><td class="py-3.5 pr-4 pl-1 font-mono text-slate-950 font-bold whitespace-nowrap"><span class="flex items-center gap-1.5"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock w-3.5 h-3.5 text-slate-400 shrink-0" aria-hidden="true"><path d="M12 6v6l4 2"></path><circle cx="12" cy="12" r="10"></circle></svg>27/05/2026</span></td><td class="py-3.5 px-4 text-slate-800 font-extrabold max-w-[170px] truncate" title="DB101: Thiết kế &amp; Quản trị SQL">Thiết kế &amp; Quản trị SQL</td><td class="py-3.5 px-4 font-mono text-slate-650 font-bold leading-none uppercase">DB101</td><td class="py-3.5 px-4 font-sans text-xs"><span class="inline-flex items-center gap-1 bg-emerald-50 text-emerald-700 border border-emerald-100 text-[10px] font-bold px-2 py-0.5 rounded-lg uppercase whitespace-nowrap">Có mặt</span></td><td class="py-3.5 px-4 font-mono text-slate-600 font-bold text-[10px] whitespace-nowrap"><span class="bg-slate-100 text-slate-700 px-2 py-0.5 rounded-md text-[9.5px]">QR + GPS</span></td><td class="py-3.5 px-2 text-right"><button class="inline-flex items-center gap-1 bg-blue-50 hover:bg-blue-100 text-blue-700 font-extrabold px-2.5 py-1 rounded-lg text-[9.5px] border-none tracking-tight transition-all active:scale-95 cursor-pointer"><span>Xem chi tiết</span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-right w-3.5 h-3.5 text-blue-600 shrink-0" aria-hidden="true"><path d="m9 18 6-6-6-6"></path></svg></button></td></tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="hidden lg:flex lg:col-span-4 bg-slate-100/50 border border-dashed border-slate-350 rounded-3xl p-8 text-center flex-col justify-center items-center h-[340px] text-slate-400 space-y-2 select-none">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-history w-8 h-8 text-slate-300 animate-pulse" aria-hidden="true"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"></path><path d="M3 3v5h5"></path><path d="M12 7v5l4 2"></path></svg>
                    <h5 class="text-xs font-black uppercase text-slate-500">Xem chi tiết lần điểm danh</h5>
                    <p class="text-[10px] max-w-[180px] font-semibold leading-relaxed">Nhấp chuột chọn một dòng nhật ký để xem chi tiết thông số toạ độ địa lý, trạng thái bảo mật của buổi học.</p>
                </div>
            </div>
        </div>
    </div>
    
    {{-- MOBILE HISTORY --}}
    <div class="lg:hidden w-full h-full font-sans">
        <div class="p-4 space-y-4 animate-in fade-in slide-in-from-bottom-2 duration-300">
            <div class="bg-gradient-to-br from-blue-600 via-indigo-650 to-indigo-800 text-white rounded-2xl p-4.5 relative overflow-hidden shadow-md border border-blue-500/30">
                <div class="absolute right-[-10px] bottom-[-10px] w-36 h-36 bg-white/10 rounded-full blur-3xl pointer-events-none"></div>
                <div class="absolute right-4 top-4 flex flex-col items-end opacity-40 font-mono text-[8px] select-none text-white/85"><div class="w-8 h-1 bg-white/60 mb-0.5 rounded-xs"></div><div class="w-6 h-1 bg-white/60 mb-0.5 rounded-xs"></div><div class="w-7 h-1 bg-white/60 rounded-xs"></div></div>
                <span class="inline-flex items-center gap-1.5 px-2.5 py-1 bg-white/10 backdrop-blur-md rounded-full text-[9px] font-extrabold uppercase tracking-widest mb-3.5 border border-white/15">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-graduation-cap w-3.5 h-3.5 text-blue-200" aria-hidden="true"><path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z"></path><path d="M22 10v6"></path><path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5"></path></svg> 
                    Cao đẳng Kỹ thuật Cao Thắng
                </span>
                <h1 class="text-lg font-black text-white leading-tight tracking-tight">Chào Trần Minh Hoàng! 👋</h1>
                <p class="text-[10.5px] text-blue-100/90 font-medium mt-1.5 leading-relaxed">Lớp hành chính: <strong class="text-white font-black">CĐ Kỹ thuật Phần mềm 23A</strong>. Duy trì tỷ lệ chuyên cần trên <strong class="text-amber-300 font-black">80%</strong> để bảo toàn điều kiện thi học phần khoa CNTT.</p>
                <div class="mt-4 pt-3 border-t border-white/10 flex items-center justify-between">
                    <div class="flex gap-0.5 opacity-30 select-none">
                        <div class="bg-white h-4" style="width: 1px;"></div><div class="bg-white h-4" style="width: 2.5px;"></div><div class="bg-white h-4" style="width: 1px;"></div><div class="bg-white h-4" style="width: 1.5px;"></div><div class="bg-white h-4" style="width: 4px;"></div><div class="bg-white h-4" style="width: 1px;"></div><div class="bg-white h-4" style="width: 2px;"></div><div class="bg-white h-4" style="width: 1.5px;"></div><div class="bg-white h-4" style="width: 1px;"></div><div class="bg-white h-4" style="width: 3px;"></div><div class="bg-white h-4" style="width: 1.5px;"></div><div class="bg-white h-4" style="width: 1px;"></div>
                    </div>
                    <span class="text-[9px] font-mono text-white/40 tracking-widest leading-none font-bold">RFID ENCRYPTED</span>
                </div>
            </div>

            <div class="bg-white border border-blue-100 rounded-2xl p-4 shadow-sm relative overflow-hidden">
                <div class="absolute top-0 right-0 bg-blue-600 text-white font-black text-[9px] uppercase tracking-widest px-3 py-1.5 rounded-bl-xl flex items-center gap-1.5 shadow-sm leading-none"><span class="w-2 h-2 bg-white rounded-full animate-ping"></span>CỔNG ĐIỂM DANH MỞ</div>
                <div class="flex items-center gap-1.5 text-blue-600 select-none"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock w-4 h-4 shrink-0" aria-hidden="true"><path d="M12 6v6l4 2"></path><circle cx="12" cy="12" r="10"></circle></svg><span class="text-[10px] font-bold uppercase tracking-widest leading-none">Cơ chế địa định vị SAMS</span></div>
                <div class="space-y-2 mt-4">
                    <h4 class="text-[8.5px] font-black text-slate-400 uppercase tracking-widest leading-none">Lớp học hiện tại</h4>
                    <h3 class="text-base font-black text-slate-900 leading-snug">NET301: Lý thuyết Mạng Máy Tính</h3>
                    <div class="bg-slate-50 rounded-xl p-3.5 border border-slate-100 mt-2.5 space-y-2 text-[11px] text-slate-600 font-semibold">
                        <div class="flex items-center gap-2.5"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user w-3.5 h-3.5 text-slate-400 shrink-0" aria-hidden="true"><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg><span>Giảng viên học phần: <span class="font-bold text-slate-800">TS. Lê Quang Linh</span></span></div>
                        <div class="flex items-center gap-2.5"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-map-pin w-3.5 h-3.5 text-slate-400 shrink-0" aria-hidden="true"><path d="M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0"></path><circle cx="12" cy="10" r="3"></circle></svg><span>Phòng học lý thuyết: <span class="font-bold text-slate-800">Cơ sở A.205 (Lab A lầu 2)</span></span></div>
                        <div class="flex items-center gap-2.5"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock w-3.5 h-3.5 text-slate-400 shrink-0" aria-hidden="true"><path d="M12 6v6l4 2"></path><circle cx="12" cy="12" r="10"></circle></svg><span>Thời gian hết hạn khóa: <span class="text-red-500 font-bold font-mono bg-red-50 border border-red-100 rounded px-1.5 py-0.5">00:00</span></span></div>
                    </div>
                </div>
                <div class="mt-4 pt-3 border-t border-slate-100">
                    <button class="focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none focus:ring-blue-500 px-4 py-2 w-full h-12 bg-blue-600 hover:bg-blue-750 text-white font-extrabold cursor-pointer shadow-lg shadow-blue-500/10 rounded-xl text-xs gap-2 border-none flex items-center justify-center active:scale-[0.98] transition-all animate-pulse" id="mob-dash-btn"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-qr-code w-4.5 h-4.5 shrink-0 text-white stroke-[2.5]" aria-hidden="true"><rect width="5" height="5" x="3" y="3" rx="1"></rect><rect width="5" height="5" x="16" y="3" rx="1"></rect><rect width="5" height="5" x="3" y="16" rx="1"></rect><path d="M21 16h-3a2 2 0 0 0-2 2v3"></path><path d="M21 21v.01"></path><path d="M12 7v3a2 2 0 0 1-2 2H7"></path><path d="M3 12h.01"></path><path d="M12 3h.01"></path><path d="M12 16v.01"></path><path d="M16 12h1"></path><path d="M21 12v.01"></path><path d="M12 21v-1"></path></svg>ĐIỂM DANH GPS/QR NGAY</button>
                </div>
            </div>

            <div class="bg-white border border-slate-100 rounded-2xl p-4 shadow-xs">
                <h3 class="text-xs font-black text-slate-800 uppercase tracking-widest mb-3">Tỷ Lệ Chuyên Cần Tổng Quan</h3>
                <div class="flex items-center justify-between gap-3">
                    <div class="relative shrink-0 w-24 h-24 flex items-center justify-center">
                        <svg class="w-full h-full transform -rotate-90">
                            <circle cx="48" cy="48" r="38" stroke="#F1F5F9" stroke-width="8" fill="transparent"></circle>
                            <circle cx="48" cy="48" r="38" stroke="#2563EB" stroke-width="8" fill="transparent" stroke-dasharray="238.76104167282426" stroke-dashoffset="18.145839167134632" stroke-linecap="round" class="transition-all duration-500"></circle>
                        </svg>
                        <div class="absolute flex flex-col items-center">
                            <span class="text-base font-black text-slate-850 leading-none">92.4%</span>
                            <span class="text-[8px] text-slate-400 font-bold uppercase tracking-wider mt-0.5">Tích luỹ</span>
                        </div>
                    </div>
                    <div class="flex-1 grid grid-cols-2 gap-2">
                        <div class="p-2 bg-slate-50/50 rounded-xl border border-slate-100 text-center flex flex-col justify-center"><span class="block text-[8px] text-slate-400 font-extrabold uppercase">Có mặt</span><span class="text-xs font-black text-slate-800 mt-1 font-mono">68 / 72 tiết</span></div>
                        <div class="p-2 bg-slate-50/50 rounded-xl border border-slate-100 text-center flex flex-col justify-center"><span class="block text-[8px] text-slate-400 font-extrabold uppercase">Vắng</span><span class="text-xs font-black text-red-600 mt-1 font-mono">4 tiết vắng</span></div>
                        <div class="p-2 bg-slate-50/50 rounded-xl border border-slate-100 text-center flex flex-col justify-center"><span class="block text-[8px] text-slate-400 font-extrabold uppercase">Đi muộn</span><span class="text-xs font-black text-amber-600 mt-1 font-mono">3 tiết trễ</span></div>
                        <div class="p-2 bg-slate-50/50 rounded-xl border border-slate-100 text-center flex flex-col justify-center"><span class="block text-[8px] text-slate-400 font-extrabold uppercase">Có phép</span><span class="text-xs font-black text-blue-600 mt-1 font-mono">1 tiết phép</span></div>
                    </div>
                </div>
            </div>

            <div class="space-y-2.5">
                <div class="flex items-center justify-between"><h3 class="text-xs font-black text-slate-800 uppercase tracking-widest">Thời Khóa Biểu Hôm Nay</h3><span class="text-[10px] font-bold text-slate-400">Thứ sáu, 05/06</span></div>
                <div class="space-y-2">
                    <div class="bg-white border-l-4 border-blue-500 rounded-xl p-3 border-r border-y border-slate-100 flex items-center justify-between gap-2 shadow-xs"><div class="space-y-1"><h4 class="text-xs font-black text-slate-800">NET301: Lý thuyết Mạng Máy Tính</h4><p class="text-[10px] text-slate-500 flex items-center gap-1 font-medium"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock w-3 h-3 text-slate-400" aria-hidden="true"><path d="M12 6v6l4 2"></path><circle cx="12" cy="12" r="10"></circle></svg> Tiết 4-6 (08:00) • TS. Lê Quang Linh • A.205</p></div><span class="shrink-0 text-[10px] font-black text-blue-600 px-2 py-1 rounded-md bg-blue-50">Đang học</span></div>
                    <div class="bg-white border-l-4 border-slate-300 rounded-xl p-3 border-r border-y border-slate-100 flex items-center justify-between gap-2 shadow-xs"><div class="space-y-1"><h4 class="text-xs font-black text-slate-800">DB101: Thiết kế &amp; Quản trị SQL</h4><p class="text-[10px] text-slate-500 flex items-center gap-1 font-medium"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock w-3 h-3 text-slate-400" aria-hidden="true"><path d="M12 6v6l4 2"></path><circle cx="12" cy="12" r="10"></circle></svg> Tiết 7-9 (13:15) • Thầy Lê Hoàng Đạt • A.201</p></div><span class="shrink-0 text-[10px] font-black text-slate-400 px-2 py-1 rounded-md bg-slate-50">Chưa học</span></div>
                </div>
            </div>

            <div class="bg-amber-50 border border-amber-200 rounded-xl p-3 flex items-start gap-2.5">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-triangle-alert w-5 h-5 text-amber-500 shrink-0 mt-0.5" aria-hidden="true"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"></path><path d="M12 9v4"></path><path d="M12 17h.01"></path></svg>
                <div class="space-y-1 flex-1">
                    <h4 class="text-[10px] font-black text-amber-800 uppercase tracking-widest leading-none">Rủi ro chuyên cần học phần</h4>
                    <p class="text-xs text-amber-800 font-semibold leading-relaxed">Môn <strong class="text-amber-950">PH102: Vật lý đại cương 2</strong> của bạn vắng mặt 4 buổi, tỉ lệ còn <span class="text-red-650 font-black">72%</span>.</p>
                    <button class="mt-2 text-[10px] font-black bg-amber-500 text-white rounded-lg px-2.5 py-1 hover:bg-amber-600 cursor-pointer border-none" id="warning-class-action-btn">Gửi chứng từ giải trình xin nghỉ phép</button>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>
