import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.js',
        './app/Livewire/**/*.php',
    ],

    theme: {
        extend: {
            colors: {
                primary: '#004ac6',
                'on-primary': '#ffffff',
                'primary-container': '#2563eb',
                'on-primary-container': '#eeefff',
                'primary-fixed': '#dbe1ff',
                'primary-fixed-dim': '#b4c5ff',
                'on-primary-fixed': '#00174b',
                'on-primary-fixed-variant': '#003ea8',
                secondary: '#5a5f62',
                'on-secondary': '#ffffff',
                'secondary-container': '#dce0e4',
                'on-secondary-container': '#5e6367',
                tertiary: '#006242',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#007d55',
                'on-tertiary-container': '#bdffdb',
                error: '#ba1a1a',
                'on-error': '#ffffff',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                background: '#f8f9ff',
                'on-background': '#0b1c30',
                surface: '#f8f9ff',
                'on-surface': '#0b1c30',
                'on-surface-variant': '#434655',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#eff4ff',
                'surface-container': '#e5eeff',
                'surface-container-high': '#dce9ff',
                'surface-container-highest': '#d3e4fe',
                'surface-variant': '#d3e4fe',
                outline: '#737686',
                'outline-variant': '#c3c6d7',
                'alert-container': '#fff0ef',
            },
            fontFamily: {
                sans: ['Outfit', 'Figtree', ...defaultTheme.fontFamily.sans],
                'headline-md': ['Outfit', ...defaultTheme.fontFamily.sans],
                'body-md': ['Outfit', ...defaultTheme.fontFamily.sans],
                'display-lg': ['Outfit', ...defaultTheme.fontFamily.sans],
                'label-md': ['Outfit', ...defaultTheme.fontFamily.sans],
                'headline-sm': ['Outfit', ...defaultTheme.fontFamily.sans],
                'stat-lg': ['Outfit', ...defaultTheme.fontFamily.sans],
                'body-lg': ['Outfit', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'display-lg': ['30px', { lineHeight: '38px', fontWeight: '700', letterSpacing: '0' }],
                'label-md': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em' }],
                'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'stat-lg': ['36px', { lineHeight: '44px', fontWeight: '700' }],
                'body-lg': ['16px', { lineHeight: '24px', fontWeight: '500' }],
            },
            spacing: {
                gutter: '1.5rem',
                'stack-sm': '0.5rem',
                'stack-md': '1rem',
                'sidebar-width': '300px',
            },
        },
    },

    plugins: [forms],
};
