import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.js',
        './app/Livewire/**/*.php',
        // Add pages directory explicitly to trigger Vite watch
        './resources/views/pages/**/*.blade.php',
    ],
    safelist: [
        'bg-blue-600', 'bg-violet-600', 'bg-orange-600', 'bg-green-600', 'bg-pink-600',
        'hover:bg-blue-700', 'hover:bg-violet-700', 'hover:bg-orange-700', 'hover:bg-green-700', 'hover:bg-pink-700',
        'ring-blue-500/20', 'ring-violet-500/20', 'ring-orange-500/20', 'ring-green-500/20', 'ring-pink-500/20',
        'shadow-blue-500/5', 'shadow-violet-500/5', 'shadow-orange-500/5', 'shadow-green-500/5', 'shadow-pink-500/5',
        'shadow-blue-500/10', 'shadow-violet-500/10', 'shadow-orange-500/10', 'shadow-green-500/10', 'shadow-pink-500/10',
        'bg-[#DBEAFE]', 'text-[#2563EB]', 
        'bg-[#FEF3C7]', 'text-[#D97706]',
        'bg-[#F1F5F9]', 'text-[#64748B]',
        'bg-[#22C55E]', 'text-[#22C55E]',
        'bg-[#F59E0B]', 'text-[#F59E0B]',
        'bg-[#EF4444]', 'text-[#EF4444]',
    ],

    theme: {
        extend: {
            colors: {
                // Clean SaaS palette: neutral slate base + single blue accent.
                primary: '#2563eb',
                'on-primary': '#ffffff',
                'primary-container': '#1d4ed8',
                'on-primary-container': '#eff6ff',
                'primary-fixed': '#dbeafe',
                'primary-fixed-dim': '#bfdbfe',
                'on-primary-fixed': '#172554',
                'on-primary-fixed-variant': '#1e40af',
                secondary: '#475569',
                'on-secondary': '#ffffff',
                'secondary-container': '#e2e8f0',
                'on-secondary-container': '#334155',
                tertiary: '#059669',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#10b981',
                'on-tertiary-container': '#064e3b',
                error: '#dc2626',
                'on-error': '#ffffff',
                'error-container': '#fee2e2',
                'on-error-container': '#991b1b',
                background: '#f8fafc',
                'on-background': '#0f172a',
                surface: '#f8fafc',
                'on-surface': '#0f172a',
                'on-surface-variant': '#64748b',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#f8fafc',
                'surface-container': '#f1f5f9',
                'surface-container-high': '#eef2f7',
                'surface-container-highest': '#e2e8f0',
                'surface-variant': '#e2e8f0',
                outline: '#94a3b8',
                'outline-variant': '#e2e8f0',
                'alert-container': '#fef2f2',
            },
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                'headline-md': ['Inter', ...defaultTheme.fontFamily.sans],
                'body-md': ['Inter', ...defaultTheme.fontFamily.sans],
                'display-lg': ['Inter', ...defaultTheme.fontFamily.sans],
                'label-md': ['Inter', ...defaultTheme.fontFamily.sans],
                'headline-sm': ['Inter', ...defaultTheme.fontFamily.sans],
                'stat-lg': ['Inter', ...defaultTheme.fontFamily.sans],
                'body-lg': ['Inter', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'display-lg': ['30px', { lineHeight: '38px', fontWeight: '700', letterSpacing: '0' }],
                'label-md': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em' }],
                'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'stat-lg': ['36px', { lineHeight: '44px', fontWeight: '700' }],
                'body-lg': ['16px', { lineHeight: '24px', fontWeight: '500' }],
            },
            spacing: {
                gutter: '1.5rem',
                'stack-sm': '0.5rem',
                'stack-md': '1rem',
                'sidebar-width': '260px',
            },
        },
    },

    plugins: [forms],
};
